#!/bin/sh

###
#
# DynDns updatescript by Steffen Vogel (info@steffenvogel.de)
# 
# dependencies: bind9utils (nslookup & nsupdate), wget, grep
#
###

# Private keyfile for authentification with the NS
KEYNAME="info.steffenvogel.de."
KEY="gDlXSZtESw78I47O68UEigpPofn0XbpSpo5Vba+9IY38EYagPO/2C2ChlZL+AvtN/ozRdra+p3+wLOKvVvqdrA=="

# The domain to update
DOMAIN="d.eta.li"

# The host to update
#HOST="laptop"
HOST=`hostname`

# The NS
#NS="ns0.y0x.org"
NS="83.169.1.58"

# Get netip
IP=`wget http://checkip.dyndns.org/ -q -O - | grep -Eo '\<[[:digit:]]{1,3}(\.[[:digit:]]{1,3}){3}\>'`

# Time to live value in seconds for the alias rr
TTL=120


# Update!
nsupdate -y "$KEYNAME:$KEY" -v <<- EOF
	server $NS
	update delete $HOST.$DOMAIN. A
	update add $HOST.$DOMAIN. $TTL A $IP
	show
	send

	EOF

# Check record
DNSIP=`host $HOST.$DOMAIN $NS | grep 'has address' | grep -Eo '\<[[:digit:]]{1,3}(\.[[:digit:]]{1,3}){3}\>'`
if [ "$DNSIP" = "$IP" ]; then
	echo "updated dns rr successfully"
	exit 0
else
	echo "error during dns rr update!" >&2
	exit 1
fi
