#!/bin/bash

###
#
# SDDNS updatescript by Steffen Vogel (info@steffenvogel.de)
#
# dependencies: curl, grep
#
################################################################################
# Settings

# Password
PW=Robens123wg

# Hostname
HOST=wg

# Zone
ZONE=0l.de

# Get netip
IP=$(wget http://checkip.dyndns.org/ -q -O - | grep -Eo '\<[[:digit:]]{1,3}(\.[[:digit:]]{1,3}){3}\>')
echo "Got netip: $IP"

################################################################################
# Expert settings

# Time to live value in seconds for the alias rr
TTL=120

# Class
CLASS=IN

# Type
TYPE=A

# Record data
RDATA=$IP

################################################################################
# Do not touch anything under this!

URL="http://d.0l.de/update.xml?host=$HOST&zone=$ZONE&ttl=$TTL&class=$CLASS&type=$TYPE&rdata=$RDATA&pw=$PW"

echo "Updating record: $URL"
curl "$URL"
